### ISSUE TITLE
If there's a need to get VirtualBox VM to use host's DNS

### ISSUE THREAD

**Issue by darren-a** [RX-M/classfiles#1]
Not sure if anyone's been bitten by this (or whether it's worth putting in student notes) but using my cellphone as a wifi hotspot I found I had to set natdnshostresolver1 to get dns resolution working properly.

https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm
> --natdnshostresolver<1-N> on|off: This setting makes the NAT engine use the host's resolver mechanisms to handle DNS requests. Please see Section 9.11.5, “Enabling DNS proxy in NAT mode” for detailsx).> 

Solution (on OSX) was to run:
`VBoxManage modifyvm "VM name" --natdnshostresolver1 on`

per comments here:

https://superuser.com/questions/641933/how-to-get-virtualbox-vms-to-use-hosts-dns

**Comment by ronaldpetty** [comment]
Thanks Darren,

Was the machine working at all before?  We often run into issues where machines lose their mind regarding DNS if it goes to sleep (aka you go to lunch).

**Comment by darren-a** [comment]
Yes - probably due to me working in Starbucks and I closed the VM by saving system state then got it fired up again in my car. I expect it was the stop and restart of the VM itself which solved this. At the time it was enough for me to simply get out. Other than that it's worked really well with none of the usual shared c+p problems I've seen before ;)

**Comment by RandyAbernethy** [comment]
DNS resolution has gone a little wacky on us even in NUC based clusters inside RX-M at 1 market. All good notes here but closing the ticket as I have added Darren's note to the lab setup md
