### ISSUE TITLE
unattended-update ubuntu 16.04

### ISSUE THREAD

**Issue by ronaldpetty** [RX-M/classfiles#2]
Probably need to disable unattended-update so the VM starts faster.   Probably just a good idea to rebuild with newer quest tools installed anyways.

https://github.com/chef/bento/issues/609

**Comment by RandyAbernethy** [comment]
closing this because we are moving to AWS instances as our primary lab env with (soon) local Ubuntu 18.04 as the back up. Will certainly want to make sure auto update is off on the 18.04 image though.
